export interface Categories {
  idCategory: String;
  strCategory: String;
  strCategoryThumb: String;
  strCategoryDescription: String;
}


export interface Meals {
idMeal: String | null,
strMeal: String | null,
strDrinkAlternate: String | null,
strCategory: String | null,
strArea: String | null,
strInstructions:String | null,
strMealThumb: String | null,
strTags: String | null,
strYoutube: String | null,
strIngredient1: String | null,
strIngredient2: String | null,
strIngredient3: String | null,
strIngredient4: String | null,
strIngredient5: String | null,
strIngredient6: String | null,
strIngredient7: String | null,
strIngredient8: String | null,
strIngredient9: String | null,
strIngredient10: String | null,
strIngredient11: String | null,
strIngredient12: String | null,
strIngredient13: String | null,
strIngredient14: String | null,
strIngredient15: String | null,
strIngredient16: String | null,
strIngredient17: String | null,
strIngredient18: String | null,
strIngredient19: String | null,
strIngredient20: String | null,
strMeasure1: String | null,
strMeasure2: String | null,
strMeasure3: String | null,
strMeasure4: String | null,
strMeasure5: String | null,
strMeasure6: String | null,
strMeasure7: String | null,
strMeasure8: String | null,
strMeasure9: String | null,
strMeasure10: String | null,
strMeasure11: String | null,
strMeasure12: String | null,
strMeasure13: String | null,
strMeasure14: String | null,
strMeasure15: String | null,
strMeasure16: String | null,
strMeasure17: String | null,
strMeasure18: String | null,
strMeasure19: String | null,
strMeasure20: String | null,
strSource: String | null,
dateModified: String | null,
}